### PR TITLE
Support Integers with bitwidth of 11

### PR DESCRIPTION
**Pull request by dave-juicelabs**
Sample code.

; <label>:1401                                    ; preds = %1395
  %1402 = trunc i32 %1399 to i11
  %1403 = lshr i11 440, %1402
  %1404 = and i11 %1403, 1
  %1405 = icmp ne i11 %1404, 0
  br label %1406

The issue initially presented with "Unexpected integer bitwidth 11."

NOTE: I do not like this implementation. I am adding this PR to get feedback for a better approach.

### CODE REVIEW

**Comment by HansKristian-Work** [comment]
How is this code generated, and is this even legal DXIL?

**Comment by HansKristian-Work** [comment]
DXC doesn't allow it at least:
```
float main(nointerpolation int a : A) : SV_Target
{
	min12int b = min12int(a);
	return float(b);
}
```

```
/tmp/test.hlsl:3:2: warning: min12int is promoted to int16_t
        min12int b = min12int(a);
        ^
/tmp/test.hlsl:3:15: warning: min12int is promoted to int16_t
        min12int b = min12int(a);
```

**Comment by dave-juicelabs** [comment]
I am not sure how the DXIL is being generated but this is coming from a AAA game studio I am working with. I am currently trying to get more information on the original source.

The code itself looks like it can be easily done with a simple AND instruction with 0x3FF but as I am just delving in to vkd3d-proton and dxil, I am unsure how to replace the code appropriately to try alternatives.

**Comment by dave-juicelabs** [comment]
@HansKristian-Work 

Here is a trimmed hlsl file of the original that reproduces the issue.

To compile it:

`dxc /E func1 /T cs_6_0 /Xpc /O3 /Gfa /all_resources_bound -HV 2016 -Fc <<assembly file>> <<input file>>`

The switch statement is the issue.

```static const uint constant_1 = 1 ; 
static const uint constant_2 = 2 ; 
static const uint constant_3 = 3 ; 
static const uint constant_7 = 7 ; 
static const uint constant_10 = 10 ; 
static const uint constant_11 = 11 ; 

cbuffer buffer1 : register ( b0 ) 
{ 
    uint cbSwitch ;
} ; 

struct struct1 
{ 
    float4 value1 ; 
} ; 

cbuffer buffer2 : register ( b1 ) 
{ 
    struct1 g_struct1 ; 
} 

RWTexture2DArray < float3 > out1 : register ( u0 ) ; 

[ numthreads ( 8 , 8 , 1 ) ] 
void func1 (  ) 
{ 
    const float3 variable1 = float3( 1.0f, 1.0f, 1.0f);
    
    bool variable3 = true ; 
    switch ( cbSwitch ) 
    { 
        case constant_1 : 
        case constant_2 : 
        case constant_3 : 
        case constant_7 : 
        case constant_10 : 
        case constant_11 : 
        variable3 = false ; 
        break ; 
    } 
    
    if ( variable3 ) 
    {
        out1 [ variable1 ] = float3(0, 0, 0);
    } 
    else
    {
        out1 [ variable1 ] = float3(1, 1, 1);
    }
}

**Comment by dave-juicelabs** [comment]
I updated the code after seeing what was happening in the source. This basically generalizes the integer but I am not sure about the 16-bit support. Does that mean any integer <= 16 bits will require the 16 bit capability. Also, I am fairly certain this will need some testing to make sure everything is correct.

**Comment by dave-juicelabs** [comment]
Made this PR without really reading in to the SPIRV and Vulkan SPIRV specs. I think the appropriate change would be to convert the 11bit integers to 16bit integers during the conversion. Will create a new PR when those changes are done.

**Comment by HansKristian-Work** [comment]
The codegen here is nonsensical. This has to be a DXC bug somehow, since I can get it to create any integer width by just changing the last switch case value, e.g.:

```
; <label>:7                                       ; preds = %0
  %8 = zext i32 %5 to i33
  %9 = lshr i33 4294966712, %8
  %10 = and i33 %9, 1
  %11 = icmp eq i33 %10, 0
  br i1 %11, label %13, label %12, !dx.controlflow.hints !13
```

**Comment by dave-juicelabs** [comment]
There is a -1 above that section that makes this make sense. Took me a bit to understand it myself.

%8 = %5 - 1
%9 = 440 >> %8
%10 = %9 & 1
if(%10 == 1) ...

440 = ~(((1 << constant_1) | (1 << constant_2) | (1 << constant_3) | (1 << constant_7) | (1 << constant_10) | (1 << constant_11)) >> 1) & ((1 << 11) - 1)

Now how the compiler figured that out from a switch statement, I am unsure but it works.

**Pull request closed without merging**
